"""Create tables with relationships

Revision ID: 43b907b5514a
Revises: 78136d158ba9
Create Date: 2026-09-06 23:13:04.433075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b907b5514a'
down_revision = '78136d158ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_bios_speaker_id_speakers'), 'bios', 'speakers', ['speaker_id'], ['id'])
    op.create_foreign_key(op.f('fk_sessions_event_id_events'), 'sessions', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sessions_event_id_events'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_bios_speaker_id_speakers'), 'bios', type_='foreignkey')
    # ### end Alembic commands ###
